export const TABLE_ACTIONS = {
  EDIT_SEARCH_QUERY: "EDIT_SEARCH_QUERY",
  APPLY_FILTER: "APPLY_FILTER",
  RESET_FILTERS: "RESET_FILTERS",
  REMOVE_FILTER: "REMOVE_FILTER",
  CHANGE_PAGE_NUMBER: "CHANGE_PAGE_NUMBER",
};
